### ISSUE TITLE
incorrect table name "question_answer_stats"

### ISSUE THREAD

**Issue by danmarsden** [thoriqadillah/essaysimilarity#5]
all tables implemented within a plugin must use the plugin frankenstyle name as a prefix "question_answer_stats" is incorrect - it should be something like "qtype_essaysimilarity_stats"

note this is an approval blocker in the plugins db.

**Comment by thoriqadillah** [comment]
should I make `upgrade.php` to solve this issue or just edit the db name in `install.xml`?

**Comment by danmarsden** [comment]
if you have existing sites using your plugin already, you might need to write the upgrade script, but if it's your own site and you're happy to manage that manually, you won't need to write the upgrade.php script... but in futre (after the plugin lands in the moodle.org plugins db) - you would need to write an upgrade script for any changes to the database structure.
