### ISSUE TITLE
consider adding github actions support, it's free and very easy.

### ISSUE THREAD

**Issue by danmarsden** [thoriqadillah/essaysimilarity#6]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by thoriqadillah** [comment]
I'm sorry, I was unfamiliar with github action (I still am).
Question: is the script is general purpose and just plug and play or should I modify something to work to this repo? Thank you in advance

**Comment by danmarsden** [comment]
The script is quite general purpose. It just needs to be copied into the right place in github. Just give it a go, you will probably find it makes sense once you play with it a bit.

**Comment by thoriqadillah** [comment]
Done

**Comment by thoriqadillah** [comment]
Hi, i am opening this issue again to ask some question
I already create the github action script in the repo. And the result is failed everytime, and it looks mostly because indentation on my code style. Is it a blocker for plugin approval too?

**Comment by danmarsden** [comment]
no - most of the stuff that the codechecker reports as "error" are not blockers for approval - just room for improvement over time - in particular as the moodle.org plugins db reports on errors/warnings that appear in your code. If it starts reporting issues with 3rd party files you've embedded in the plugin, make sure the path to the external library is correct in your thirdpartylibs.xml file as those files are excluded from the moodle coding guideline tests.

**Comment by thoriqadillah** [comment]
Alright. All issue of the approval block has been resolved then
