### ISSUE TITLE
use PhpOfffice?

### ISSUE THREAD

**Issue by danmarsden** [thoriqadillah/essaysimilarity#8]
Is this use statement correct? - are you actually using phpoffice helpers in the class?

https://github.com/thoriqadillah/essaysimilarity/blob/main/renderer.php#L27

**Comment by thoriqadillah** [comment]
whoops, forgot about that. I think it was because I tried something with auto completion while typing `html` and I thought it was the right import, and forgot to delete the import. It's removed now
